# Generated by Django 5.1.3 on 2024-11-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('endereco', models.CharField(max_length=250)),
                ('profissao', models.CharField(max_length=250)),
                ('indicado_por', models.CharField(max_length=250)),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viuvo', 'Viúvo')], default='solteiro', max_length=10)),
                ('inicio_tratamento', models.DateField()),
                ('termino_tratamento', models.DateField(blank=True, null=True)),
                ('interrupcao', models.DateField(blank=True, null=True)),
                ('anotações', models.TextField()),
                ('tc', models.DateTimeField()),
                ('ts', models.DateTimeField()),
                ('pa_max', models.PositiveIntegerField()),
                ('pa_min', models.PositiveIntegerField()),
                ('sensibilidade_anestisia', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3)),
                ('sensibilidade_antibiotico', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3)),
                ('data', models.DateField()),
                ('dente', models.CharField(max_length=10)),
                ('tratamento_realidado', models.CharField(max_length=100)),
                ('tempo', models.CharField(max_length=10)),
                ('debito', models.CharField(max_length=10)),
                ('credito', models.CharField(max_length=10)),
                ('saldo', models.CharField(max_length=10)),
            ],
        ),
    ]
